"""
Hermes UI Perception, Layout Understanding, and Visual Targeting Engine.
"""

from .models import (
    ActionType,
    BoundingBox,
    CandidateMatch,
    CompositeComponent,
    ElementType,
    InteractionPoint,
    LayoutType,
    Point,
    PreconditionValidationResult,
    RegionType,
    ResolutionResult,
    ResolutionStatus,
    SafeClickRegion,
    SpatialRelation,
    TargetQuery,
    UIContainer,
    UIElement,
    UIRegion,
    UISnapshot,
    UIState,
    UITree,
    VerificationResult,
    VisibilityState,
)
from .precondition_validator import TargetPreconditionValidator
from .service import HermesUIService, get_ui_service

__all__ = [
    "ActionType",
    "BoundingBox",
    "CandidateMatch",
    "CompositeComponent",
    "ElementType",
    "HermesUIService",
    "InteractionPoint",
    "LayoutType",
    "Point",
    "PreconditionValidationResult",
    "RegionType",
    "ResolutionResult",
    "ResolutionStatus",
    "SafeClickRegion",
    "SpatialRelation",
    "TargetPreconditionValidator",
    "TargetQuery",
    "UIContainer",
    "UIElement",
    "UIRegion",
    "UISnapshot",
    "UIState",
    "UITree",
    "VerificationResult",
    "VisibilityState",
    "get_ui_service",
]
